//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sphaera.Web.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sphaera.Web.Server.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ подлинности клиента не прошел проверку! Зайдите на главную страницу сайта и повторите операцию..
        /// </summary>
        public static string AntiForgeryTokenError {
            get {
                return ResourceManager.GetString("AntiForgeryTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется авторизация.
        /// </summary>
        public static string AuthorizationRequired {
            get {
                return ResourceManager.GetString("AuthorizationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка провайдера авторизации..
        /// </summary>
        public static string AuthProviderError {
            get {
                return ResourceManager.GetString("AuthProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается загрузить ресурсы &quot;{0}&quot;..
        /// </summary>
        public static string CanntLoadResource {
            get {
                return ResourceManager.GetString("CanntLoadResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить экземпляр HttpClient..
        /// </summary>
        public static string ClientCreationError {
            get {
                return ResourceManager.GetString("ClientCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данное действие невозможно..
        /// </summary>
        public static string CurrentActionNotPossible {
            get {
                return ResourceManager.GetString("CurrentActionNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка обращения к базе данных.
        /// </summary>
        public static string DbError {
            get {
                return ResourceManager.GetString("DbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответ от сервиса не содержит данных..
        /// </summary>
        public static string EmptyResult {
            get {
                return ResourceManager.GetString("EmptyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение перечисления с именем {0} не определено в типе {1}..
        /// </summary>
        public static string EnumNotDefined {
            get {
                return ResourceManager.GetString("EnumNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исключение.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие невозможно.
        /// </summary>
        public static string ExecutionNotPossible {
            get {
                return ResourceManager.GetString("ExecutionNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У Вас отсутствуют права доступа к данной информации..
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует контекст запроса..
        /// </summary>
        public static string HttpContextIsAbsent {
            get {
                return ResourceManager.GetString("HttpContextIsAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка {0} при обработке запроса &quot;{1}&quot;..
        /// </summary>
        public static string HttpError {
            get {
                return ResourceManager.GetString("HttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщите, пожалуйста, об ошибке по электронной почте или по телефонам службы технической поддержки..
        /// </summary>
        public static string KnownError {
            get {
                return ResourceManager.GetString("KnownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден или поврежден файл конфигурации log4net.config..
        /// </summary>
        public static string Log4NetConfigNotFound {
            get {
                return ResourceManager.GetString("Log4NetConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не загружено ни одного плагина. Работа сервера не возможна..
        /// </summary>
        public static string NoPluginLoaded {
            get {
                return ResourceManager.GetString("NoPluginLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не прошел аутентификацию..
        /// </summary>
        public static string NotAuthenticated {
            get {
                return ResourceManager.GetString("NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аргумент &quot;{0}&quot; не может быть пустым..
        /// </summary>
        public static string NullNotAllowed {
            get {
                return ResourceManager.GetString("NullNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница не найдена.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрашиваемая страница не найдена..
        /// </summary>
        public static string RequestedPageNotFound {
            get {
                return ResourceManager.GetString("RequestedPageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрашиваемый внешний ресурс не доступен..
        /// </summary>
        public static string RequestedResourceNotFound {
            get {
                return ResourceManager.GetString("RequestedResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данное действие запрещено системой безопасности..
        /// </summary>
        public static string SecurityEsception {
            get {
                return ResourceManager.GetString("SecurityEsception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер не найден.
        /// </summary>
        public static string ServerNotFound {
            get {
                return ResourceManager.GetString("ServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип не является перечислением..
        /// </summary>
        public static string TypeNotEnum {
            get {
                return ResourceManager.GetString("TypeNotEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неавторизованный клиент..
        /// </summary>
        public static string UnauthorizedClient {
            get {
                return ResourceManager.GetString("UnauthorizedClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неподдерживаемый тип плагина &quot;{0}&quot;..
        /// </summary>
        public static string UnknownPluginType {
            get {
                return ResourceManager.GetString("UnknownPluginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует идентификатор пользователя..
        /// </summary>
        public static string UserIdNotFound {
            get {
                return ResourceManager.GetString("UserIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка {0} ({1}) при вызове Web API: &quot;{2}&quot;..
        /// </summary>
        public static string WebApiError {
            get {
                return ResourceManager.GetString("WebApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин или пароль.
        /// </summary>
        public static string WrongLoginOrPassword {
            get {
                return ResourceManager.GetString("WrongLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не авторизованы для выполнения данного действия..
        /// </summary>
        public static string YouAreNotAuthToExecCurrentAction {
            get {
                return ResourceManager.GetString("YouAreNotAuthToExecCurrentAction", resourceCulture);
            }
        }
    }
}
