//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sphaera.Web.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sphaera.Web.Api.Resources.Titles", typeof(Titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О Программе.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАО СФЕРА.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата последнего обновления сайта: {0}.
        /// </summary>
        public static string ChangeDateString {
            get {
                return ResourceManager.GetString("ChangeDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руководитель муниципального образования.
        /// </summary>
        public static string ChiefMunicipal {
            get {
                return ResourceManager.GetString("ChiefMunicipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руководитель региона.
        /// </summary>
        public static string ChiefRegion {
            get {
                return ResourceManager.GetString("ChiefRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гражданин.
        /// </summary>
        public static string Citizen {
            get {
                return ResourceManager.GetString("Citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл конфигурации.
        /// </summary>
        public static string ConfigString {
            get {
                return ResourceManager.GetString("ConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контроллер.
        /// </summary>
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018 - ЗАО СФЕРА.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес сервера идентификации пользователей: {0}.
        /// </summary>
        public static string IdmString {
            get {
                return ResourceManager.GetString("IdmString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        public static string PortalAdmin {
            get {
                return ResourceManager.GetString("PortalAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор службы или организации.
        /// </summary>
        public static string StaffAdmin {
            get {
                return ResourceManager.GetString("StaffAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диспетчер муниципальной службы или организации.
        /// </summary>
        public static string StaffDispatcher {
            get {
                return ResourceManager.GetString("StaffDispatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руководитель муниципальной службы или организации.
        /// </summary>
        public static string StaffSupervisor {
            get {
                return ResourceManager.GetString("StaffSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система 112.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия сайта: {0}.
        /// </summary>
        public static string VersionString {
            get {
                return ResourceManager.GetString("VersionString", resourceCulture);
            }
        }
    }
}
