export const GET_REMINDER_LIST = 'GET_REMINDER_LIST';
export const REMINDER_LIST_LOADED = 'REMINDER_LIST_LOADED';

export const GET_REMINDERS_CONTENT = 'GET_REMINDERS_CONTENT';
export const REMINDERS_CONTENT_LOADED = 'REMINDERS_CONTENT_LOADED';

export const SET_REMINDER_NODE_EXPANDED = 'SET_REMINDER_NODE_EXPANDED';
export const SET_REMINDER_NODE_COLLAPSED = 'SET_REMINDER_NODE_COLLAPSED';